version: '3.9'

services:
  database:
    container_name: database_postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.db/data:/var/lib/postgresql/data
      - ./.db/tsearch_data:/usr/share/postgresql/13/tsearch_data
      - ./.db/csv:/usr/share/postgresql/13/csv

  api:
    build:
      context: .
      target: development
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ./.env
    environment:
      DB_HOST: "database_postgres"

    command: sh -c "/bin/wait-for-it.sh database_postgres:5432 --timeout=60 -- npm run migration:run && npm run start:debug"
    depends_on:
      - database
