version: '3.9'

services:
  database:
    container_name: database_postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.db/data:/var/lib/postgresql/data
      - ./.db/tsearch_data:/usr/share/postgresql/13/tsearch_data
